### ISSUE TITLE
3D geometries

### ISSUE THREAD

**Issue by AxelD1** [microsoft/svirl#7]
Hi all,

I would like to do Ginzburg-Landau simulations on 3 dimensional geometries, as shown for instance in the reference paper. Is there any update on when 3D simulations could be implemented in Svirl?

Thanks!

Kind regards,
Axel

**Comment by ivan-sadovsky** [comment]
Axel, right now we don't have 3D solver implemented in Svirl. Are you interested in simulations of a particular physical problem?

**Comment by AxelD1** [comment]
Hi Ivan. Thank you for your response. Do you have any idea on whether a 3D solver can be implemented in the near future? I would like to study curvature induced effects, as in e.g. https://doi.org/10.1103/PhysRevB.86.104508.

**Comment by ivan-sadovsky** [comment]
@AxelD1, currently we are not working on 3D implementation. 

Note that if you are interested $\lambda/\xi \to \infty$ limit only, we have another (3D) solver described in [this paper](https://arxiv.org/abs/1409.8340).
